name: Java CI with Gradle

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
      - name: Set up JDK
        uses: actions/setup-java@v3.0.0
        with:
          distribution: adopt
          java-version: 11
      - name: Build FastMOTD
        run: ./gradlew build
      - name: Upload FastMOTD
        uses: actions/upload-artifact@v3.0.0
        with:
          name: FastMOTD
          path: "build/libs/FastMOTD*.jar"
